#!/usr/bin/env python3
"""Generate deploy/accel-ppp/cloud-init.yaml from the canonical source files.

The cloud-init user-data must be a SELF-CONTAINED blob (the VPS has no access to
this repo), so it embeds the setup script, the accel-ppp template, and the agent.
To keep that blob from drifting from the sources, it is GENERATED here and a
unit test (tests/test_cloud_init.py) asserts the committed file equals
``render()`` — so any edit to a source file fails CI until the yaml is rebuilt.

Embedded files are base64 (``encoding: b64``) so the YAML stays trivially valid
(single-line content, no indentation/escaping pitfalls) and verifiable without a
YAML parser. The one human-edited block — the ``# >>> SET ME`` activation env —
stays plaintext so the operator can fill it in before pasting.

Regenerate:
    python3 deploy/accel-ppp/build_cloud_init.py > deploy/accel-ppp/cloud-init.yaml
"""
from __future__ import annotations

import base64
from pathlib import Path

HERE = Path(__file__).resolve().parent

# (source path relative to HERE, destination path on the VPS, perms)
# Destination layout matches what setup-radius-vps.sh expects: it resolves the
# template + agent relative to its own dir ($(dirname "$0")), and the runcmd
# runs it from /opt/hoberadius/accel-ppp/.
BASE = "/opt/hoberadius/accel-ppp"
EMBEDDED = [
    ("setup-radius-vps.sh",   f"{BASE}/setup-radius-vps.sh",      "0755"),
    ("accel-ppp.conf.tmpl",   f"{BASE}/accel-ppp.conf.tmpl",      "0644"),
    ("agent/vps_agent.py",    f"{BASE}/agent/vps_agent.py",       "0755"),
    ("agent/__init__.py",     f"{BASE}/agent/__init__.py",        "0644"),
]

ENV_DEST = f"{BASE}/accel-activation.env"

# The ONLY operator-edited block. Plaintext so it's obvious what to fill in.
ENV_CONTENT = """\
# >>> SET ME before first boot (paste this whole file as the VPS user-data).
# These mirror docs: panel adds the customer + VPS IP and auto-creates the
# Cloudflare A record for SUBDOMAIN BEFORE you create the VPS.
VPS_IP=
SUBDOMAIN=
RADIUS_SECRET=
CERTBOT_EMAIL=admin@hoberadius.com
# Optional overrides (safe defaults shown):
WG_DATA_PORT=51830
POOL_GATEWAY=10.20.0.1
POOL_RANGE=10.20.0.2-10.20.255.254
DNS_WAIT_TIMEOUT=300
"""

# Source the env (export every var) then run the activation script, logging to
# a file the operator can inspect post-boot.
RUNCMD = (f'set -a; . {ENV_DEST}; set +a; '
          f'bash {BASE}/setup-radius-vps.sh 2>&1 | tee -a /var/log/hoberadius-activation.log')

# NOTE: keep this header ASCII-only. The embedded files are base64 (pure
# ASCII), so the whole generated yaml is ASCII and the drift test can compare
# render() to the committed file without any encoding ambiguity.
HEADER = """\
#cloud-config
# ============================================================================
# HobeRadius -- accel-ppp DATA-connection activation (cloud-init user-data)
# GENERATED by deploy/accel-ppp/build_cloud_init.py -- DO NOT hand-edit the b64
# blobs. Edit the source files under deploy/accel-ppp/ and regenerate:
#   python3 deploy/accel-ppp/build_cloud_init.py > deploy/accel-ppp/cloud-init.yaml
#
# USE: fill in the >>> SET ME values in the accel-activation.env block below,
# then paste this whole file into the provider's user-data field at VPS
# creation. First boot installs accel-ppp + certbot, waits for DNS, issues the
# cert, and starts accel-ppp -- zero-touch. (Manual fallback: run
# setup-radius-vps.sh by hand -- see deploy/accel-ppp/README.md.)
# ============================================================================
"""


def _indent_block(text: str, spaces: int) -> str:
    pad = " " * spaces
    # Keep a trailing newline per line; blank lines stay blank (no trailing ws).
    return "".join((pad + ln if ln else "") + "\n" for ln in text.splitlines())


def render() -> str:
    """Deterministic cloud-config string. Reads the canonical source files."""
    out: list[str] = [HEADER, "write_files:\n"]

    # 1) The operator-edited env (plaintext block scalar).
    out.append(f"  - path: {ENV_DEST}\n")
    out.append("    permissions: '0644'\n")
    out.append("    content: |\n")
    out.append(_indent_block(ENV_CONTENT, 6))

    # 2) The embedded files (base64, single-line content). Normalize CRLF→LF
    # so the VPS always receives LF (a CRLF bash shebang breaks on Linux) and
    # the output is stable regardless of how the repo was checked out.
    for rel, dest, perms in EMBEDDED:
        raw = (HERE / rel).read_bytes().replace(b"\r\n", b"\n")
        b64 = base64.b64encode(raw).decode("ascii")
        out.append(f"  - path: {dest}\n")
        out.append(f"    permissions: '{perms}'\n")
        out.append("    encoding: b64\n")
        out.append(f"    content: {b64}\n")

    # 3) Run it on first boot.
    out.append("\nruncmd:\n")
    out.append(f"  - [ bash, -lc, \"{RUNCMD}\" ]\n")
    return "".join(out)


if __name__ == "__main__":  # pragma: no cover
    import sys
    sys.stdout.write(render())
