# services_data.py — بيانات وهمية لصفحة الخدمات
# ستُستبدل لاحقاً بـ DB query من جدول ServiceCatalogItem / CustomerServiceEntitlement

SERVICES_MOCK = [
    # ── إدارة المشتركين ────────────────────────────────────────────
    {
        "key": "subscribers",
        "name": "المشتركون",
        "category": "subscribers",
        "cat_label": "إدارة المشتركين",
        "description": "إدارة حسابات المشتركين، تفعيل، تعطيل، تغيير باقة",
        "icon": "👥",
        "status": "active",
        "limits": {"label": "حد المشتركين", "max": 500, "current": 230},
    },
    {
        "key": "online_sessions",
        "name": "المتصلون الآن",
        "category": "subscribers",
        "cat_label": "إدارة المشتركين",
        "description": "مراقبة المستخدمين المتصلين لحظياً وقطع الاتصال",
        "icon": "📡",
        "status": "active",
        "limits": {"label": "جلسات متزامنة", "max": 100, "current": 45},
    },
    {
        "key": "cards",
        "name": "البطاقات",
        "category": "subscribers",
        "cat_label": "إدارة المشتركين",
        "description": "حزم بطاقات hotspot، توليد وطباعة، استيراد CSV",
        "icon": "🃏",
        "status": "active",
        "limits": {"label": "بطاقات نشطة", "max": 1000, "current": 320},
    },
    {
        "key": "recharge_cards",
        "name": "بطاقات الشحن",
        "category": "subscribers",
        "cat_label": "إدارة المشتركين",
        "description": "بطاقات بقيمة مالية لشحن رصيد المشتركين",
        "icon": "💳",
        "status": "frozen",
        "limits": {"label": "بطاقات متاحة", "max": 200, "current": 0},
    },
    {
        "key": "card_users",
        "name": "مستخدمو البطاقات",
        "category": "subscribers",
        "cat_label": "إدارة المشتركين",
        "description": "حسابات تتعامل حصرياً بالبطاقات",
        "icon": "👤",
        "status": "hidden",
        "limits": {"label": "حسابات نشطة", "max": 50, "current": 12},
    },
    {
        "key": "marketplace",
        "name": "سوق البطاقات",
        "category": "subscribers",
        "cat_label": "إدارة المشتركين",
        "description": "بيع باقات للموزعين بأسعار مرونة",
        "icon": "🏪",
        "status": "unavailable",
        "limits": None,
    },
    # ── الباقات والشبكة ────────────────────────────────────────────
    {
        "key": "plans",
        "name": "باقات الإنترنت",
        "category": "network",
        "cat_label": "الباقات والشبكة",
        "description": "تعريف باقات الوقت والكوتا والمختلطة",
        "icon": "📦",
        "status": "active",
        "limits": {"label": "باقات نشطة", "max": 50, "current": 18},
    },
    {
        "key": "bandwidth_profiles",
        "name": "نطاقات السرعة",
        "category": "network",
        "cat_label": "الباقات والشبكة",
        "description": "ملفات سرعة تنزيل ورفع قابلة لإعادة الاستخدام",
        "icon": "⚡",
        "status": "active",
        "limits": {"label": "ملفات السرعة", "max": 30, "current": 12},
    },
    {
        "key": "nas_devices",
        "name": "أجهزة الشبكة",
        "category": "network",
        "cat_label": "الباقات والشبكة",
        "description": "إدارة أجهزة RADIUS — MikroTik وسيسكو",
        "icon": "🔌",
        "status": "active",
        "limits": {"label": "أجهزة مسجّلة", "max": 20, "current": 5},
    },
    {
        "key": "ip_pools",
        "name": "مجمعات IP",
        "category": "network",
        "cat_label": "الباقات والشبكة",
        "description": "نطاقات عناوين IP وتوزيعها على المشتركين",
        "icon": "🌐",
        "status": "active",
        "limits": {"label": "IPs مستخدمة", "max": 1000, "current": 230},
    },
    # ── المالية ────────────────────────────────────────────────────
    {
        "key": "finance_center",
        "name": "المركز المالي",
        "category": "finance",
        "cat_label": "المالية",
        "description": "فواتير، كوبونات، تحصيل، سجل محاسبي",
        "icon": "💰",
        "status": "active",
        "limits": {"label": "معاملات الشهر", "max": None, "current": 145},
    },
    {
        "key": "distributors",
        "name": "الموزعون",
        "category": "finance",
        "cat_label": "المالية",
        "description": "حسابات الموزعين والديون والأرباح",
        "icon": "🤝",
        "status": "active",
        "limits": {"label": "موزعون نشطون", "max": 10, "current": 3},
    },
    # ── التواصل ────────────────────────────────────────────────────
    {
        "key": "communications",
        "name": "الاتصالات",
        "category": "comms",
        "cat_label": "التواصل",
        "description": "قوالب رسائل وحملات إشعارات جماعية",
        "icon": "📢",
        "status": "active",
        "limits": {"label": "رسائل الشهر", "max": 1000, "current": 234},
    },
    {
        "key": "whatsapp",
        "name": "واتساب",
        "category": "comms",
        "cat_label": "التواصل",
        "description": "إشعارات OTP وانتهاء الاشتراك ونفاد الكوتا",
        "icon": "💬",
        "status": "active",
        "limits": {"label": "رسائل اليوم", "max": 100, "current": 28},
    },
    # ── البنية التحتية ────────────────────────────────────────────
    {
        "key": "vpn_accounts",
        "name": "حسابات VPN",
        "category": "infra",
        "cat_label": "البنية التحتية",
        "description": "حسابات VPN مرتبطة بتخصيصات الترخيص",
        "icon": "🔐",
        "status": "active",
        "limits": {"label": "حسابات VPN", "max": 50, "current": 15},
    },
    {
        "key": "wireguard",
        "name": "WireGuard",
        "category": "infra",
        "cat_label": "البنية التحتية",
        "description": "إعداد وإدارة واجهة WireGuard والـ peers",
        "icon": "🛡️",
        "status": "active",
        "limits": {"label": "peers نشطة", "max": 20, "current": 8},
    },
    {
        "key": "setup_wizard",
        "name": "معالج الإعداد",
        "category": "infra",
        "cat_label": "البنية التحتية",
        "description": "ربط راوتر MikroTik وضبطه خطوة بخطوة",
        "icon": "🧙",
        "status": "active",
        "limits": None,
    },
    # ── النظام ────────────────────────────────────────────────────
    {
        "key": "backups",
        "name": "النسخ الاحتياطية",
        "category": "system",
        "cat_label": "النظام",
        "description": "نسخ احتياطي محلي أو سحابي مع جدولة تلقائية",
        "icon": "💾",
        "status": "active",
        "limits": {"label": "نسخ محفوظة", "max": 30, "current": 12},
    },
    {
        "key": "reports",
        "name": "التقارير",
        "category": "system",
        "cat_label": "النظام",
        "description": "تقارير الجلسات والمالية والأحداث",
        "icon": "📊",
        "status": "active",
        "limits": {"label": "تقارير الشهر", "max": None, "current": 5},
    },
    {
        "key": "api_tokens",
        "name": "API Tokens",
        "category": "system",
        "cat_label": "النظام",
        "description": "رموز وصول للـ API مع rotation بدون انقطاع",
        "icon": "🔑",
        "status": "unavailable",
        "limits": None,
    },
    {
        "key": "webhooks",
        "name": "Webhooks",
        "category": "system",
        "cat_label": "النظام",
        "description": "endpoints استقبال أحداث مع توقيع HMAC",
        "icon": "🔗",
        "status": "unavailable",
        "limits": None,
    },
]
