"""fleet.registry.script_render — render the unified RouterOS provisioning script.

Phase-3 task T3: take a CHR row + a generated/derived set of WireGuard keys and
binding addresses, plus fleet-constant template config, and emit a fully-baked
``.rsc`` ready to push onto the device via the bootstrap channel
(P3-T4 owns the push; we own the bytes).

The contract is the headline of ``docs/chr_fleet/06_ONBOARDING_WIZARD.md``:

    > Same script, different credentials.

The renderer enforces that contract structurally — the only template variables
declared as **per-CHR** below are the ones documented in §6.5.1; everything else
flows from ``RouterosTemplateConfig`` which is fleet-constant. A unit test
(``tests/fleet_p3/test_script_render.py``) renders two distinct CHRs and asserts
the line-diff is precisely the set of per-CHR bindings — if a fleet-constant
ever leaks into the per-CHR set, the test will fail loudly.

Phase-3 scope
-------------
- Pure rendering. Key generation lives in P3-T2 (``wg_keys.py``,
  ``secrets_vault.py``); the bootstrap push lives in P3-T4
  (``bootstrap_push.py``). The renderer takes already-generated key material as
  input; it does NOT touch a vault or call out.
- No DB writes. ``render_chr_script`` is functional: it reads from a
  ``FleetChrNode`` row + a ``ChrKeyMaterial`` value object and returns text.

Vault discipline
----------------
The CHR-side WireGuard *private* keys (``wg_mgmt_privkey``, ``wg_data_privkey``)
flow through this renderer because the script must install them on the device.
They are still kept **out of the panel DB**: the caller pulls them from the
vault by reference (``wg_keypair_ref``) just-in-time for the render, then drops
them. This module never logs them and never writes them anywhere — it returns
the rendered text to its caller, full stop.
"""

from __future__ import annotations

import ipaddress
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape

if TYPE_CHECKING:  # pragma: no cover - typing only
    from fleet.registry.models_chr import FleetChrNode


# ─────────────────────────────────────────────────────────────────────────────
# Binding boundaries — documented in 06 §6.5.1
# ─────────────────────────────────────────────────────────────────────────────

#: The Jinja variables that legitimately vary between two CHRs. The
#: only-bindings-differ test treats any per-line diff that isn't a value of
#: one of these names as a regression — i.e. a fleet-constant has accidentally
#: been split per CHR. Keep this list IDENTICAL to the §6.5.1 "per-CHR?" rows.
PER_CHR_BINDINGS: tuple[str, ...] = (
    "WG_MGMT_PRIVKEY",
    "WG_MGMT_ADDR",
    "WG_DATA_PRIVKEY",
    "WG_DATA_ADDR",
    "WG_DATA_ADDR_IP",   # derived from WG_DATA_ADDR; used as RADIUS src-address
    "ROUTER_IDENTITY",
    "CHR_PUBLIC_IP",
    "WAN_IFACE",
)

#: Headline subset surfaced by the wizard UI / state-machine docs (§6.3).
#: The full per-CHR delta is in ``PER_CHR_BINDINGS``; this short list is just
#: the operator-facing four the wizard form maps to.
HEADLINE_PER_CHR_BINDINGS: tuple[str, ...] = (
    "WG_MGMT_PRIVKEY",
    "WG_MGMT_ADDR",
    "CHR_PUBLIC_IP",
    "ROUTER_IDENTITY",
)


# ─────────────────────────────────────────────────────────────────────────────
# Inputs
# ─────────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class ChrKeyMaterial:
    """Per-CHR secrets + addresses the renderer must inject.

    Generated by P3-T2 (key generation) immediately before render; the caller
    is responsible for fetching ``mgmt_privkey`` / ``data_privkey`` from the
    vault by ``onboarding_jobs.wg_keypair_ref``. Both ``mgmt_addr`` and
    ``data_addr`` must be CIDR strings (e.g. ``10.99.0.11/32``) — the data
    tunnel needs the bare IP separately for RADIUS ``src-address``, which the
    renderer derives so callers do not have to think about it.
    """

    mgmt_privkey: str
    """CHR-side wg-mgmt private key (base64). Vault-sourced; not stored in DB."""

    mgmt_addr: str
    """wg-mgmt address with prefix, e.g. ``10.99.0.11/32``. RFC 1918."""

    data_privkey: str
    """CHR-side wg-data private key (base64). Vault-sourced; not stored in DB."""

    data_addr: str
    """wg-data address with prefix, e.g. ``10.98.0.11/32``. RFC 1918."""

    wan_iface: str = "ether1"
    """Router interface on the public IP. Defaults to ``ether1``; the wizard's
    "Initial RouterOS reach" step is expected to override this when detected."""


@dataclass(frozen=True)
class RouterosTemplateConfig:
    """Fleet-constant inputs to the unified template (§6.5.1 "no" rows).

    These are IDENTICAL across every CHR — that's the whole point of the
    unified template. They are loaded from app config / Settings UI in
    production (a later integrator phase); here we expose a dataclass so
    tests + callers have a single import surface, and so they can be reviewed
    in one place.

    The defaults below are documentation-shaped placeholders chosen to match
    the worked example in 06_ONBOARDING_WIZARD.md. Production should override
    every field; the test fixtures do.
    """

    # ── panel-side WireGuard CONTROL endpoint ────────────────────────────
    panel_wg_pubkey: str = "<PANEL_WG_PUBKEY>"
    panel_wg_endpoint: str = "panel.hoberadius.internal"
    panel_wg_addr: str = "10.99.0.1"

    # ── proxy-side WireGuard DATA endpoint ───────────────────────────────
    proxy_wg_pubkey: str = "<PROXY_WG_PUBKEY>"
    proxy_wg_endpoint: str = "proxy.hoberadius.internal"
    proxy_wg_addr: str = "10.98.0.1"

    # ── RADIUS shared secret (one secret across the fleet; §6.5.1 note) ──
    chr_shared_secret: str = "<CHR_SHARED_SECRET>"

    # ── shared certs and pool policy ─────────────────────────────────────
    sstp_cert_name: str = "hobe-sstp-cert"
    ike_cert_name: str = "hobe-ike-cert"
    client_supernet: str = "10.0.0.0/8"
    dns_push: str = "1.1.1.1,1.0.0.1"
    gw_local_addr: str = "10.0.0.1"

    # ── panel read-only API user (live-metrics poller) ───────────────────
    # When BOTH api_user and api_password are non-empty, the unified
    # script provisions a ``read``-group user reachable only over
    # wg-mgmt. Empty in either field → the API block is skipped.
    api_user: str = ""
    api_password: str = ""
    api_port: int = 8443
    # feat/chr-auto-scoped-mgmt-user — dedicated scoped management user
    # group (see the unified template §11 for the policy audit).
    api_group: str = "hobe-fleet-mgmt"

    # ── shared client pool + PPP profile (feat/chr-unified-provisioning-complete)
    # Same name + ranges on every node so a subscriber roaming/failing-
    # over between nodes keeps the same Framed-IP and the same profile.
    # See docs/CUSTOMER_RADIUS_TUNNEL_DESIGN.md §10.2.
    ip_pool_name: str = "hobe-fleet-pool"
    ip_pool_ranges: str = "10.50.0.10-10.50.255.254"
    ppp_profile_name: str = "hobe-fleet-default"

    # ── user-WireGuard server (role: vpn_wireguard) ─────────────────────
    # Listens on UDP for end-user dialers. The CHR auto-generates the
    # private key on `add` (we deliberately do NOT push one — the panel
    # reads the matching public key back via heartbeat). 51822 chosen so
    # it doesn't collide with wg-mgmt (51820) or wg-data (51821).
    wg_users_port: int = 51822
    wg_users_addr: str = "10.51.0.1/24"

    # ── self-lockout rollback window (§0a / §12) ────────────────────────
    # Time after the rollback scheduler is armed before it fires.
    # The script's last block CANCELS the scheduler — clean runs never
    # see the rollback. If the admin loses connectivity mid-apply, the
    # CHR boots back into the pre-apply snapshot after this delay.
    safemode_rollback_delay: str = "3m"


# ─────────────────────────────────────────────────────────────────────────────
# Jinja environment
# ─────────────────────────────────────────────────────────────────────────────
_TEMPLATE_DIR: Path = Path(__file__).resolve().parent / "templates"
_TEMPLATE_NAME: str = "chr_unified.rsc.j2"


def _build_env(template_dir: Path = _TEMPLATE_DIR) -> Environment:
    """Configure Jinja: strict undefined (any missing binding is a render error)
    and autoescape OFF (this is RouterOS config, not HTML)."""
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=select_autoescape(disabled_extensions=("j2", "rsc")),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=False,
        lstrip_blocks=False,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _ip_without_mask(cidr: str) -> str:
    """Strip the ``/mask`` from a CIDR literal; raise ``ValueError`` on garbage.

    The template uses both the CIDR form (for ``/ip address add address=...``)
    AND the bare IP (for RADIUS ``src-address=...``). Forcing CIDR-in / IP-out
    here means callers can't accidentally store the wrong shape.
    """
    if "/" not in cidr:
        # Validate it parses as a bare IP, then return as-is.
        ipaddress.ip_address(cidr.strip())
        return cidr.strip()
    iface = ipaddress.ip_interface(cidr.strip())
    return str(iface.ip)


#: Default ports per WG plane. MUST match ``infra_settings._DEFAULT_PORTS``.
#: Duplicated here (not imported) to keep this module Flask-free — the
#: renderer must work in pure-Python tests that don't boot the app.
_DEFAULT_ENDPOINT_PORTS = {
    "PANEL_WG_ENDPOINT": 51820,
    "PROXY_WG_ENDPOINT": 51821,
}


def _split_endpoint(value: str, *, default_port: int) -> tuple[str, int]:
    """Parse a ``host`` / ``host:port`` / ``[ipv6]:port`` literal into the
    two fields RouterOS needs separately.

    Critical: RouterOS' ``/interface wireguard peers`` rejects ``host:port``
    inside ``endpoint-address=`` — the colon-port causes the peer to land
    with ``current-endpoint-address=""`` and no handshake ever fires. The
    only correct shape is ``endpoint-address=<host>`` and ``endpoint-port=<n>``
    separately. This helper is the single splitter used at render time so
    the bug can't recur from any code path.
    """
    raw = (value or "").strip()
    if not raw:
        return "", default_port
    if raw.startswith("["):
        # bracketed IPv6
        close = raw.find("]")
        if close == -1:
            return raw, default_port  # malformed; let StrictUndefined / on-CHR import surface
        host = raw[: close + 1]
        rest = raw[close + 1 :]
        if rest.startswith(":") and rest[1:].isdigit():
            return host, int(rest[1:])
        return host, default_port
    if raw.count(":") == 1:
        host, _, port_str = raw.partition(":")
        if port_str.isdigit():
            port = int(port_str)
            if 1 <= port <= 65535:
                return host, port
    # No port suffix (or multi-colon junk) — return host alone with default.
    return raw, default_port


def build_bindings(
    node: "FleetChrNode",
    keys: ChrKeyMaterial,
    template_cfg: RouterosTemplateConfig,
) -> dict[str, Any]:
    """Assemble the full binding dict the template expects.

    Returns a plain ``dict[str, str]`` ready to pass into ``Environment.render``.
    Centralising this means there is exactly one place that translates the
    domain types (``FleetChrNode`` + ``ChrKeyMaterial`` + ``RouterosTemplateConfig``)
    into template variable names — the test introspects this function to verify
    the boundary documented in §6.5.1.
    """
    # Split host:port → (host, port) for both WG peer endpoints. The template
    # references the HOST / PORT split bindings (NOT the raw combined ones);
    # see the module docstring for why RouterOS forbids host:port inside
    # endpoint-address.
    panel_host, panel_port = _split_endpoint(
        template_cfg.panel_wg_endpoint,
        default_port=_DEFAULT_ENDPOINT_PORTS["PANEL_WG_ENDPOINT"],
    )
    proxy_host, proxy_port = _split_endpoint(
        template_cfg.proxy_wg_endpoint,
        default_port=_DEFAULT_ENDPOINT_PORTS["PROXY_WG_ENDPOINT"],
    )

    # Per-node role set. Empty list ⇒ "all roles enabled" — the back-compat
    # rule from app/services/node_roles.py. We resolve here so the template
    # gets a concrete iterable (not a None) and StrictUndefined never trips.
    roles_set = _resolve_node_roles(node)
    return {
        # ── per-CHR (PER_CHR_BINDINGS) ──────────────────────────────────────
        "WG_MGMT_PRIVKEY":  keys.mgmt_privkey,
        "WG_MGMT_ADDR":     keys.mgmt_addr,
        "WG_DATA_PRIVKEY":  keys.data_privkey,
        "WG_DATA_ADDR":     keys.data_addr,
        "WG_DATA_ADDR_IP":  _ip_without_mask(keys.data_addr),
        "ROUTER_IDENTITY":  node.name,
        "CHR_PUBLIC_IP":    node.public_ip,
        "WAN_IFACE":        keys.wan_iface,
        "NODE_ROLES_SET":   roles_set,
        # ── fleet-constant (RouterosTemplateConfig) ─────────────────────────
        "PANEL_WG_PUBKEY":     template_cfg.panel_wg_pubkey,
        # Combined form kept for backwards-compat consumers (e.g. UI display);
        # NOT referenced by the template anymore — the split bindings below are.
        "PANEL_WG_ENDPOINT":   template_cfg.panel_wg_endpoint,
        "PANEL_WG_HOST":       panel_host,
        "PANEL_WG_PORT":       panel_port,
        "PANEL_WG_ADDR":       template_cfg.panel_wg_addr,
        "PROXY_WG_PUBKEY":     template_cfg.proxy_wg_pubkey,
        "PROXY_WG_ENDPOINT":   template_cfg.proxy_wg_endpoint,
        "PROXY_WG_HOST":       proxy_host,
        "PROXY_WG_PORT":       proxy_port,
        "PROXY_WG_ADDR":       template_cfg.proxy_wg_addr,
        "CHR_SHARED_SECRET":   template_cfg.chr_shared_secret,
        "SSTP_CERT_NAME":      template_cfg.sstp_cert_name,
        "IKE_CERT_NAME":       template_cfg.ike_cert_name,
        "CLIENT_SUPERNET":     template_cfg.client_supernet,
        "DNS_PUSH":            template_cfg.dns_push,
        "GW_LOCAL_ADDR":       template_cfg.gw_local_addr,
        # ── live-metrics API user provisioning ─────────────────────────────
        "API_USER":            template_cfg.api_user,
        "API_PASSWORD":        template_cfg.api_password,
        "API_PORT":            template_cfg.api_port,
        "API_GROUP":           template_cfg.api_group,
        # ── shared client pool + PPP profile (single source of truth) ──────
        "IP_POOL_NAME":         template_cfg.ip_pool_name,
        "IP_POOL_RANGES":       template_cfg.ip_pool_ranges,
        "PPP_PROFILE_NAME":     template_cfg.ppp_profile_name,
        # ── user-WireGuard server (role: vpn_wireguard) ────────────────────
        "WG_USERS_PORT":        template_cfg.wg_users_port,
        "WG_USERS_ADDR":        template_cfg.wg_users_addr,
        # ── self-lockout rollback delay (§0a / §12) ────────────────────────
        "SAFEMODE_ROLLBACK_DELAY": template_cfg.safemode_rollback_delay,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Per-node role resolution
# ─────────────────────────────────────────────────────────────────────────────
#: Full role vocabulary (mirrors app.services.node_roles.NODE_ROLES). Listed
#: here so the renderer stays Flask-free for pure-Python tests — if the
#: import-time resolver below fails, every role is assumed enabled.
_ALL_ROLES: tuple[str, ...] = (
    "radius_transport",
    "vpn_sstp",
    "vpn_pptp",
    "vpn_ipsec",
    "vpn_wireguard",
)


def _resolve_node_roles(node: "FleetChrNode") -> set[str]:
    """Return the set of roles enabled on ``node``.

    Tries ``app.services.node_roles.enabled_roles`` first (the single
    source of truth) — that helper applies the back-compat rule ("empty
    list ⇒ all roles") consistently with the rest of the panel. If the
    import fails (tests that run the renderer outside the Flask app),
    we fall back to reading ``roles_json`` directly with the same
    semantics.
    """
    try:
        from app.services.node_roles import enabled_roles  # type: ignore
        return frozenset(enabled_roles(node))
    except Exception:  # noqa: BLE001 — keep the renderer Flask-free
        pass
    import json as _json
    raw = getattr(node, "roles_json", None) or "[]"
    try:
        loaded = _json.loads(raw) if isinstance(raw, str) else list(raw or [])
    except (TypeError, ValueError):
        loaded = []
    enabled = {r for r in loaded if r in _ALL_ROLES}
    return frozenset(enabled) if enabled else frozenset(_ALL_ROLES)


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────
def render_chr_script(
    node: "FleetChrNode",
    keys: ChrKeyMaterial,
    template_cfg: RouterosTemplateConfig | None = None,
    *,
    env: Environment | None = None,
) -> str:
    """Render the unified RouterOS provisioning script for ``node``.

    Parameters
    ----------
    node:
        The ``fleet_chr_nodes`` row whose identity + public IP go into the
        script. ``name`` becomes ``ROUTER_IDENTITY``; ``public_ip`` is
        documented in the trailing comment (not the policy itself).
    keys:
        Per-CHR WireGuard private keys + addresses (generated by P3-T2 and
        loaded from the vault just-in-time for this call).
    template_cfg:
        Fleet-constant inputs. When omitted, the dataclass defaults are used
        (suitable for tests / dry runs; production callers MUST pass a
        real config).
    env:
        Override the Jinja environment (testing hook). Defaults to the
        package-internal env that loads from ``fleet/registry/templates``.

    Returns
    -------
    str
        The fully-rendered ``.rsc`` source, including trailing newline.

    Raises
    ------
    jinja2.UndefinedError
        If any template variable is unbound — by design, because
        ``StrictUndefined`` is in effect. This is how we catch
        "forgot to add a binding" before it ever leaves the panel.
    ValueError
        If ``keys.data_addr`` is not a parseable CIDR / IP literal.
    """
    cfg = template_cfg if template_cfg is not None else RouterosTemplateConfig()
    bindings = build_bindings(node, keys, cfg)
    _assert_no_reserved_subnet_collision(bindings)
    jinja_env = env if env is not None else _build_env()
    template = jinja_env.get_template(_TEMPLATE_NAME)
    return template.render(**bindings)


def render_from_bindings(bindings: dict[str, Any], *, env: Environment | None = None) -> str:
    """Render directly from a raw binding dict. Used by tests that want to
    exercise the template independently of the ``FleetChrNode`` ORM.

    For backwards-compat with callers that only pass the combined
    ``PANEL_WG_ENDPOINT`` / ``PROXY_WG_ENDPOINT`` (the pre-split shape),
    auto-derive the ``*_HOST`` / ``*_PORT`` siblings. Explicit values in the
    bindings dict win.
    """
    enriched: dict[str, Any] = dict(bindings)
    for src, host_key, port_key, default_port in (
        ("PANEL_WG_ENDPOINT", "PANEL_WG_HOST", "PANEL_WG_PORT",
         _DEFAULT_ENDPOINT_PORTS["PANEL_WG_ENDPOINT"]),
        ("PROXY_WG_ENDPOINT", "PROXY_WG_HOST", "PROXY_WG_PORT",
         _DEFAULT_ENDPOINT_PORTS["PROXY_WG_ENDPOINT"]),
    ):
        if (host_key not in enriched or port_key not in enriched) and src in enriched:
            host, port = _split_endpoint(enriched[src], default_port=default_port)
            enriched.setdefault(host_key, host)
            enriched.setdefault(port_key, port)
    # Back-compat defaults for the newer bindings (feat/chr-unified-
    # provisioning-complete). Older test fixtures + ad-hoc callers don't
    # pass these; we supply sensible defaults so StrictUndefined doesn't
    # trip on a binding they have no reason to know about. Explicit
    # values in the dict ALWAYS win.
    enriched.setdefault("NODE_ROLES_SET", frozenset(_ALL_ROLES))
    enriched.setdefault("IP_POOL_NAME", "hobe-fleet-pool")
    enriched.setdefault("IP_POOL_RANGES", "10.50.0.10-10.50.255.254")
    enriched.setdefault("PPP_PROFILE_NAME", "hobe-fleet-default")
    enriched.setdefault("WG_USERS_PORT", 51822)
    enriched.setdefault("WG_USERS_ADDR", "10.51.0.1/24")
    enriched.setdefault("SAFEMODE_ROLLBACK_DELAY", "3m")
    # feat/chr-auto-scoped-mgmt-user — dedicated scoped management group
    # (see the unified template §11 + the policy audit in
    # fleet/registry/onboarding_service.py for the rationale).
    enriched.setdefault("API_GROUP", "hobe-fleet-mgmt")
    _assert_no_reserved_subnet_collision(enriched)
    jinja_env = env if env is not None else _build_env()
    template = jinja_env.get_template(_TEMPLATE_NAME)
    return template.render(**enriched)


def _assert_no_reserved_subnet_collision(bindings: dict[str, Any]) -> None:
    """Refuse to render a script whose PPP gateway address overlaps the
    reserved fleet subnets (10.98.0.0/24 wg-data, 10.99.0.0/24 wg-mgmt).

    ``GW_LOCAL_ADDR`` is the CHR-side PPP gateway IP — if it lands inside
    a reserved /24, the CHR answers the proxy's wg-data IP locally and
    breaks the RADIUS return path (the live 2026-06 chr-vpn-1 incident).
    ``CLIENT_SUPERNET`` is the NAT-egress supernet and is intentionally
    broad (10.0.0.0/8 by default) — it legitimately encloses the reserved
    /24s as a side effect of being large; the actual PPP client pool the
    panel writes is validated separately in
    ``app/services/speed_profiles.ensure_on_chr`` and
    ``vpn_tunnels.provision``.

    Imports are local to keep this module Flask-free for pure-Python tests.
    """
    from app.services.reserved_subnets import (
        ReservedSubnetError,
        assert_address_not_reserved,
    )
    try:
        gw = bindings.get("GW_LOCAL_ADDR")
        if gw:
            assert_address_not_reserved(str(gw), field_label="GW_LOCAL_ADDR")
    except ReservedSubnetError as exc:
        # Raise as ValueError so callers that don't import the helper still
        # get a recognisable failure — same shape as the existing strict-
        # binding ``ValueError`` the renderer already raises on bad CIDRs.
        raise ValueError(str(exc)) from exc


__all__ = [
    "PER_CHR_BINDINGS",
    "HEADLINE_PER_CHR_BINDINGS",
    "ChrKeyMaterial",
    "RouterosTemplateConfig",
    "build_bindings",
    "render_chr_script",
    "render_from_bindings",
]
