"""fleet.registry.script_render — render the unified RouterOS provisioning script.

Phase-3 task T3: take a CHR row + a generated/derived set of WireGuard keys and
binding addresses, plus fleet-constant template config, and emit a fully-baked
``.rsc`` ready to push onto the device via the bootstrap channel
(P3-T4 owns the push; we own the bytes).

The contract is the headline of ``docs/chr_fleet/06_ONBOARDING_WIZARD.md``:

    > Same script, different credentials.

The renderer enforces that contract structurally — the only template variables
declared as **per-CHR** below are the ones documented in §6.5.1; everything else
flows from ``RouterosTemplateConfig`` which is fleet-constant. A unit test
(``tests/fleet_p3/test_script_render.py``) renders two distinct CHRs and asserts
the line-diff is precisely the set of per-CHR bindings — if a fleet-constant
ever leaks into the per-CHR set, the test will fail loudly.

Phase-3 scope
-------------
- Pure rendering. Key generation lives in P3-T2 (``wg_keys.py``,
  ``secrets_vault.py``); the bootstrap push lives in P3-T4
  (``bootstrap_push.py``). The renderer takes already-generated key material as
  input; it does NOT touch a vault or call out.
- No DB writes. ``render_chr_script`` is functional: it reads from a
  ``FleetChrNode`` row + a ``ChrKeyMaterial`` value object and returns text.

Vault discipline
----------------
The CHR-side WireGuard *private* keys (``wg_mgmt_privkey``, ``wg_data_privkey``)
flow through this renderer because the script must install them on the device.
They are still kept **out of the panel DB**: the caller pulls them from the
vault by reference (``wg_keypair_ref``) just-in-time for the render, then drops
them. This module never logs them and never writes them anywhere — it returns
the rendered text to its caller, full stop.
"""

from __future__ import annotations

import ipaddress
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape

if TYPE_CHECKING:  # pragma: no cover - typing only
    from fleet.registry.models_chr import FleetChrNode


# ─────────────────────────────────────────────────────────────────────────────
# Binding boundaries — documented in 06 §6.5.1
# ─────────────────────────────────────────────────────────────────────────────

#: The Jinja variables that legitimately vary between two CHRs. The
#: only-bindings-differ test treats any per-line diff that isn't a value of
#: one of these names as a regression — i.e. a fleet-constant has accidentally
#: been split per CHR. Keep this list IDENTICAL to the §6.5.1 "per-CHR?" rows.
PER_CHR_BINDINGS: tuple[str, ...] = (
    "WG_MGMT_PRIVKEY",
    "WG_MGMT_ADDR",
    "WG_DATA_PRIVKEY",
    "WG_DATA_ADDR",
    "WG_DATA_ADDR_IP",   # derived from WG_DATA_ADDR; used as RADIUS src-address
    "ROUTER_IDENTITY",
    "CHR_PUBLIC_IP",
    "WAN_IFACE",
)

#: Headline subset surfaced by the wizard UI / state-machine docs (§6.3).
#: The full per-CHR delta is in ``PER_CHR_BINDINGS``; this short list is just
#: the operator-facing four the wizard form maps to.
HEADLINE_PER_CHR_BINDINGS: tuple[str, ...] = (
    "WG_MGMT_PRIVKEY",
    "WG_MGMT_ADDR",
    "CHR_PUBLIC_IP",
    "ROUTER_IDENTITY",
)


# ─────────────────────────────────────────────────────────────────────────────
# Inputs
# ─────────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class ChrKeyMaterial:
    """Per-CHR secrets + addresses the renderer must inject.

    Generated by P3-T2 (key generation) immediately before render; the caller
    is responsible for fetching ``mgmt_privkey`` / ``data_privkey`` from the
    vault by ``onboarding_jobs.wg_keypair_ref``. Both ``mgmt_addr`` and
    ``data_addr`` must be CIDR strings (e.g. ``10.99.0.11/32``) — the data
    tunnel needs the bare IP separately for RADIUS ``src-address``, which the
    renderer derives so callers do not have to think about it.
    """

    mgmt_privkey: str
    """CHR-side wg-mgmt private key (base64). Vault-sourced; not stored in DB."""

    mgmt_addr: str
    """wg-mgmt address with prefix, e.g. ``10.99.0.11/32``. RFC 1918."""

    data_privkey: str
    """CHR-side wg-data private key (base64). Vault-sourced; not stored in DB."""

    data_addr: str
    """wg-data address with prefix, e.g. ``10.98.0.11/32``. RFC 1918."""

    wan_iface: str = "ether1"
    """Router interface on the public IP. Defaults to ``ether1``; the wizard's
    "Initial RouterOS reach" step is expected to override this when detected."""


@dataclass(frozen=True)
class RouterosTemplateConfig:
    """Fleet-constant inputs to the unified template (§6.5.1 "no" rows).

    These are IDENTICAL across every CHR — that's the whole point of the
    unified template. They are loaded from app config / Settings UI in
    production (a later integrator phase); here we expose a dataclass so
    tests + callers have a single import surface, and so they can be reviewed
    in one place.

    The defaults below are documentation-shaped placeholders chosen to match
    the worked example in 06_ONBOARDING_WIZARD.md. Production should override
    every field; the test fixtures do.
    """

    # ── panel-side WireGuard CONTROL endpoint ────────────────────────────
    panel_wg_pubkey: str = "<PANEL_WG_PUBKEY>"
    panel_wg_endpoint: str = "panel.hoberadius.internal"
    panel_wg_addr: str = "10.99.0.1"

    # ── proxy-side WireGuard DATA endpoint ───────────────────────────────
    proxy_wg_pubkey: str = "<PROXY_WG_PUBKEY>"
    proxy_wg_endpoint: str = "proxy.hoberadius.internal"
    proxy_wg_addr: str = "10.98.0.1"

    # ── RADIUS shared secret (one secret across the fleet; §6.5.1 note) ──
    chr_shared_secret: str = "<CHR_SHARED_SECRET>"

    # ── shared certs and pool policy ─────────────────────────────────────
    sstp_cert_name: str = "hobe-sstp-cert"
    ike_cert_name: str = "hobe-ike-cert"
    client_supernet: str = "10.0.0.0/8"
    dns_push: str = "1.1.1.1,1.0.0.1"
    gw_local_addr: str = "10.0.0.1"


# ─────────────────────────────────────────────────────────────────────────────
# Jinja environment
# ─────────────────────────────────────────────────────────────────────────────
_TEMPLATE_DIR: Path = Path(__file__).resolve().parent / "templates"
_TEMPLATE_NAME: str = "chr_unified.rsc.j2"


def _build_env(template_dir: Path = _TEMPLATE_DIR) -> Environment:
    """Configure Jinja: strict undefined (any missing binding is a render error)
    and autoescape OFF (this is RouterOS config, not HTML)."""
    return Environment(
        loader=FileSystemLoader(str(template_dir)),
        autoescape=select_autoescape(disabled_extensions=("j2", "rsc")),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=False,
        lstrip_blocks=False,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _ip_without_mask(cidr: str) -> str:
    """Strip the ``/mask`` from a CIDR literal; raise ``ValueError`` on garbage.

    The template uses both the CIDR form (for ``/ip address add address=...``)
    AND the bare IP (for RADIUS ``src-address=...``). Forcing CIDR-in / IP-out
    here means callers can't accidentally store the wrong shape.
    """
    if "/" not in cidr:
        # Validate it parses as a bare IP, then return as-is.
        ipaddress.ip_address(cidr.strip())
        return cidr.strip()
    iface = ipaddress.ip_interface(cidr.strip())
    return str(iface.ip)


def build_bindings(
    node: "FleetChrNode",
    keys: ChrKeyMaterial,
    template_cfg: RouterosTemplateConfig,
) -> dict[str, Any]:
    """Assemble the full binding dict the template expects.

    Returns a plain ``dict[str, str]`` ready to pass into ``Environment.render``.
    Centralising this means there is exactly one place that translates the
    domain types (``FleetChrNode`` + ``ChrKeyMaterial`` + ``RouterosTemplateConfig``)
    into template variable names — the test introspects this function to verify
    the boundary documented in §6.5.1.
    """
    return {
        # ── per-CHR (PER_CHR_BINDINGS) ──────────────────────────────────────
        "WG_MGMT_PRIVKEY":  keys.mgmt_privkey,
        "WG_MGMT_ADDR":     keys.mgmt_addr,
        "WG_DATA_PRIVKEY":  keys.data_privkey,
        "WG_DATA_ADDR":     keys.data_addr,
        "WG_DATA_ADDR_IP":  _ip_without_mask(keys.data_addr),
        "ROUTER_IDENTITY":  node.name,
        "CHR_PUBLIC_IP":    node.public_ip,
        "WAN_IFACE":        keys.wan_iface,
        # ── fleet-constant (RouterosTemplateConfig) ─────────────────────────
        "PANEL_WG_PUBKEY":     template_cfg.panel_wg_pubkey,
        "PANEL_WG_ENDPOINT":   template_cfg.panel_wg_endpoint,
        "PANEL_WG_ADDR":       template_cfg.panel_wg_addr,
        "PROXY_WG_PUBKEY":     template_cfg.proxy_wg_pubkey,
        "PROXY_WG_ENDPOINT":   template_cfg.proxy_wg_endpoint,
        "PROXY_WG_ADDR":       template_cfg.proxy_wg_addr,
        "CHR_SHARED_SECRET":   template_cfg.chr_shared_secret,
        "SSTP_CERT_NAME":      template_cfg.sstp_cert_name,
        "IKE_CERT_NAME":       template_cfg.ike_cert_name,
        "CLIENT_SUPERNET":     template_cfg.client_supernet,
        "DNS_PUSH":            template_cfg.dns_push,
        "GW_LOCAL_ADDR":       template_cfg.gw_local_addr,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────
def render_chr_script(
    node: "FleetChrNode",
    keys: ChrKeyMaterial,
    template_cfg: RouterosTemplateConfig | None = None,
    *,
    env: Environment | None = None,
) -> str:
    """Render the unified RouterOS provisioning script for ``node``.

    Parameters
    ----------
    node:
        The ``fleet_chr_nodes`` row whose identity + public IP go into the
        script. ``name`` becomes ``ROUTER_IDENTITY``; ``public_ip`` is
        documented in the trailing comment (not the policy itself).
    keys:
        Per-CHR WireGuard private keys + addresses (generated by P3-T2 and
        loaded from the vault just-in-time for this call).
    template_cfg:
        Fleet-constant inputs. When omitted, the dataclass defaults are used
        (suitable for tests / dry runs; production callers MUST pass a
        real config).
    env:
        Override the Jinja environment (testing hook). Defaults to the
        package-internal env that loads from ``fleet/registry/templates``.

    Returns
    -------
    str
        The fully-rendered ``.rsc`` source, including trailing newline.

    Raises
    ------
    jinja2.UndefinedError
        If any template variable is unbound — by design, because
        ``StrictUndefined`` is in effect. This is how we catch
        "forgot to add a binding" before it ever leaves the panel.
    ValueError
        If ``keys.data_addr`` is not a parseable CIDR / IP literal.
    """
    cfg = template_cfg if template_cfg is not None else RouterosTemplateConfig()
    bindings = build_bindings(node, keys, cfg)
    jinja_env = env if env is not None else _build_env()
    template = jinja_env.get_template(_TEMPLATE_NAME)
    return template.render(**bindings)


def render_from_bindings(bindings: dict[str, Any], *, env: Environment | None = None) -> str:
    """Render directly from a raw binding dict. Used by tests that want to
    exercise the template independently of the ``FleetChrNode`` ORM."""
    jinja_env = env if env is not None else _build_env()
    template = jinja_env.get_template(_TEMPLATE_NAME)
    return template.render(**bindings)


__all__ = [
    "PER_CHR_BINDINGS",
    "HEADLINE_PER_CHR_BINDINGS",
    "ChrKeyMaterial",
    "RouterosTemplateConfig",
    "build_bindings",
    "render_chr_script",
    "render_from_bindings",
]
