"""HobeRadius VPS agent package (accel-ppp DATA connections, 2c skeleton)."""
from .vps_agent import (
    AgentResult,
    CommandExecutor,
    CommandResult,
    DnsWaitResult,
    FakeExecutor,
    FakeResolver,
    Resolver,
    Session,
    SystemExecutor,
    SystemResolver,
    VpsAgent,
    WireguardPeerSpec,
    build_certbot_argv,
    build_shaper_argv,
    build_wireguard_peer_argv,
    mbit_to_kbit,
    parse_sessions,
    wait_for_dns,
)

__all__ = [
    "AgentResult",
    "CommandExecutor",
    "CommandResult",
    "DnsWaitResult",
    "FakeExecutor",
    "FakeResolver",
    "Resolver",
    "Session",
    "SystemExecutor",
    "SystemResolver",
    "VpsAgent",
    "WireguardPeerSpec",
    "build_certbot_argv",
    "build_shaper_argv",
    "build_wireguard_peer_argv",
    "mbit_to_kbit",
    "parse_sessions",
    "wait_for_dns",
]
